name: crypto_helper_2
description: "Crypto pet project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.8
  candlesticks:

  #di
  provider:

  #code generation
  freezed_annotation:
  json_annotation:

  #web
  dio:
  http:



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  dart_code_metrics_presets: ^2.29.0


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
